apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollmentservices
  template:
    metadata:
      labels:
        app: enrollmentservices
    spec:
      containers:
      - name: enrollmentservices
        image: faniadev/enrollmentservices:latest
---
apiVersion: v1
kind: Service
metadata:
  name: enrollments-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: enrollmentservices
  ports:
  - name: enrollmentservices
    protocol: TCP
    port: 80
    targetPort: 80
